[build]
  command = "npm run build"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
